#!/usr/bin/env python3
"""Run EcoSat baseline, optimized, and FPGA-hybrid analyses."""

from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from simulation.config import DEFAULT_CONFIG
from simulation.power.battery_model import (
    equivalent_full_cycles_per_year,
    lifetime_extension_percent,
    watt_hours,
)
from simulation.power.energy_estimator import daily_energy_mwh, energy_per_orbit_mwh, summarize_scenario
from simulation.power.power_model import SCENARIOS, baseline_average_power_mw
from simulation.power.thermal_model import estimated_temperature_drop_c, relative_thermal_load
from simulation.utils.csv_export import write_dict_rows, write_phase_rows
from simulation.utils.plotting import generate_all_plots


RESULTS_CSV = ROOT / "results" / "csv"
RESULTS_REPORTS = ROOT / "results" / "reports"
RESULTS_GRAPHS = ROOT / "results" / "graphs"


def build_summary_rows() -> list[dict[str, float | str]]:
    baseline_power = baseline_average_power_mw()
    battery_wh = watt_hours(DEFAULT_CONFIG.battery_voltage_v, DEFAULT_CONFIG.battery_capacity_mah)
    baseline_cycles = equivalent_full_cycles_per_year(daily_energy_mwh(baseline_power), battery_wh)

    rows: list[dict[str, float | str]] = []
    for scenario in SCENARIOS:
        row = summarize_scenario(scenario, baseline_power)
        cycles = equivalent_full_cycles_per_year(daily_energy_mwh(scenario.average_power_mw), battery_wh)
        row["daily_energy_mwh"] = daily_energy_mwh(scenario.average_power_mw)
        row["battery_cycles_per_year"] = cycles
        row["battery_lifetime_extension_percent"] = lifetime_extension_percent(baseline_cycles, cycles)
        row["relative_thermal_load"] = relative_thermal_load(scenario.average_power_mw, baseline_power)
        row["estimated_temperature_drop_c"] = estimated_temperature_drop_c(row["power_savings_percent"])
        rows.append(row)
    return rows


def write_baseline_csv() -> None:
    baseline_power = baseline_average_power_mw()
    write_dict_rows(
        RESULTS_CSV / "baseline_power.csv",
        [
            {
                "scenario": "baseline_always_on",
                "average_power_mw": baseline_power,
                "energy_per_orbit_mwh": energy_per_orbit_mwh(baseline_power),
                "daily_energy_mwh": daily_energy_mwh(baseline_power),
            }
        ],
    )


def write_markdown_report(rows: list[dict[str, float | str]]) -> None:
    baseline_power = baseline_average_power_mw()
    baseline_energy = energy_per_orbit_mwh(baseline_power)
    lines = [
        "# Simulation Summary",
        "",
        "Generated by `python3 simulation/main.py`.",
        "",
        "## Baseline",
        "",
        f"- Average power: {baseline_power:.2f} mW",
        f"- Energy per orbit: {baseline_energy:.2f} mWh",
        f"- Daily energy: {daily_energy_mwh(baseline_power):.2f} mWh",
        "",
        "## Optimized Scenarios",
        "",
        "| Scenario | Avg power | Energy/orbit | Energy saved | Battery extension |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['scenario']} | {row['average_power_mw']:.2f} mW | "
            f"{row['energy_per_orbit_mwh']:.2f} mWh | "
            f"{row['energy_savings_percent']:.2f}% | "
            f"{row['battery_lifetime_extension_percent']:.2f}% |"
        )
    lines.extend(
        [
            "",
            "The FPGA-hybrid case should be presented as an extension scenario because it",
            "depends on the assumed reduction in radio active time after compression.",
            "",
        ]
    )
    RESULTS_REPORTS.mkdir(parents=True, exist_ok=True)
    (RESULTS_REPORTS / "simulation_summary.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    RESULTS_CSV.mkdir(parents=True, exist_ok=True)
    RESULTS_REPORTS.mkdir(parents=True, exist_ok=True)

    rows = build_summary_rows()
    write_baseline_csv()
    write_dict_rows(RESULTS_CSV / "optimized_power.csv", rows)
    write_dict_rows(RESULTS_CSV / "orbit_energy.csv", rows)
    write_dict_rows(RESULTS_CSV / "battery_lifetime.csv", rows)
    write_phase_rows(RESULTS_CSV / "scenario_phase_power.csv", SCENARIOS)
    write_markdown_report(rows)

    baseline_power = baseline_average_power_mw()
    battery_wh = watt_hours(DEFAULT_CONFIG.battery_voltage_v, DEFAULT_CONFIG.battery_capacity_mah)
    baseline_cycles = equivalent_full_cycles_per_year(daily_energy_mwh(baseline_power), battery_wh)
    plots = generate_all_plots(baseline_power, baseline_cycles, SCENARIOS, rows, RESULTS_GRAPHS)

    print("EcoSat simulation complete")
    for row in rows:
        print(
            f"- {row['scenario']}: {row['average_power_mw']:.2f} mW, "
            f"{row['energy_savings_percent']:.2f}% energy saved"
        )
    for plot in plots:
        print(f"- wrote {plot.relative_to(ROOT)}")
    print(f"Results written under {ROOT / 'results'}")


if __name__ == "__main__":
    main()
